mydata <- read.csv("C:\\Users\\HP\\Downloads\\forestfires (1).csv")
plot(mydata)
View(mydata)
plot(mydata$temp, mydata$wind)
plot(mydata[,9], mydata[,11])
hist(mydata$temp)
plot(mydata$temp, type = "l")
plot(mydata$X,mydata$Y, col=mydata$temp)
meantemp <- mean(mydata$temp)
print(meantemp)
write.csv(meantemp, file = "result.csv")
plot(mydata$temp, mydata$ISI)
lmfire <- line(mydata$ISI~mydata$temp)
abline(coef(lmfire))
